Style/Copyright:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
AllCops:
  EnabledByDefault: true
  Exclude:
    - 'Rakefile'
    - 'Guardfile'
    - 'config.ru'
    - 'config/**/*.rb'
    - 'config/*.rb'
    - 'db/**/*.rb'
    - 'vendor/**/*'
    - 'bin/*'
    - 'Gemfile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/support/*'
    - 'spec/support/*'