name: Test

on: [ pull_request ]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    
    - name: Dependencies
      run: |
        gem install rubocop
        bundle exec rubocop

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: 10
        postgresql db: runa_access_control_test
        postgresql user: global_production
        postgresql password: lenovo

    
    - name: Dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake

    - name: Create Database
      run: |
        rake db:setup

    - name: Run Test
      run: |
        bundle exec rspec